AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notion-updater

  Sample SAM Template for notion-updater

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NotionUpdaterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: NotionStatusUpdater
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Timeout: 900
      MemorySize: 256
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - arn:aws:ssm:ap-northeast-1:*:parameter/notion_updater/*
      Events:
        DailyTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 18 * * ? *)
      Environment:
        Variables:
          NOTION_TOKEN_PARAM: "/notion_updater/notion_token"
          DATABASE_ID_PARAM: "/notion_updater/database_id"
          PARENT_PAGE_ID_PARAM: "/notion_updater/parent_page_id"

